server:
  port: 8080
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
ignore.paths:
  - /sign-up
spring:
  application:
    name: learnVerse-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format:
          sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: 123

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB

logging:
  level:
    org:
      springframework:
        security : debug
