INSERT INTO PUBLIC.CATEGORY (ID, CREATED_DATE, MODIFIED_DATE, IS_DELETED, CODE, NAME_AR, NAME_EN) VALUES
(1, NOW(), NOW(), 0, 'ALGO', 'الخوارزميات', 'ALGORITHMS'),
(2, NOW(), NOW(), 0, 'DATA_STRUCT', 'هياكل البيانات', 'DATA STRUCTURES'),
(3, NOW(), NOW(), 0, 'DB_MGMT', 'إدارة قواعد البيانات', 'DATABASE MANAGEMENT'),
(4, NOW(), NOW(), 0, 'WEB_DEV', 'تطوير الويب', 'WEB DEVELOPMENT'),
(5, NOW(), NOW(), 0, 'MACHINE_LEARN', 'تعلم الآلة', 'MACHINE LEARNING'),
(6, NOW(), NOW(), 0, 'SYS_DESIGN', 'تصميم النظم', 'SYSTEM DESIGN'),
(7, NOW(), NOW(), 0, 'OS', 'أنظمة التشغيل', 'OPERATING SYSTEMS'),
(8, NOW(), NOW(), 0, 'NETWORKS', 'الشبكات', 'NETWORKS'),
(9, NOW(), NOW(), 0, 'SECURITY', 'الأمن السيبراني', 'CYBERSECURITY'),
(10, NOW(), NOW(), 0, 'UI_UX', 'تجربة المستخدم', 'UI/UX DESIGN'),
(11, NOW(), NOW(), 0, 'COMP_GRAPHICS', 'الرسوم البيانية', 'COMPUTER GRAPHICS'),
(12, NOW(), NOW(), 0, 'AI', 'الذكاء الاصطناعي', 'ARTIFICIAL INTELLIGENCE'),
(13, NOW(), NOW(), 0, 'CLOUD_COMP', 'الحوسبة السحابية', 'CLOUD COMPUTING'),
(14, NOW(), NOW(), 0, 'GAME_DEV', 'تطوير الألعاب', 'GAME DEVELOPMENT'),
(15, NOW(), NOW(), 0, 'SOFT_TESTING', 'اختبار البرمجيات', 'SOFTWARE TESTING'),
(16, NOW(), NOW(), 0, 'DEV_OPS', 'ديفوبس', 'DEVOPS'),
(17, NOW(), NOW(), 0, 'MOBILE_DEV', 'تطوير الهاتف المحمول', 'MOBILE DEVELOPMENT'),
(18, NOW(), NOW(), 0, 'EMBED_SYS', 'النظم المدمجة', 'EMBEDDED SYSTEMS'),
(19, NOW(), NOW(), 0, 'CRYPTO', 'التشفير', 'CRYPTOGRAPHY'),
(20, NOW(), NOW(), 0, 'BLOCKCHAIN', 'بلوكتشين', 'BLOCKCHAIN'),
(21, NOW(), NOW(), 0, 'ETHICS', 'أخلاقيات البرمجة', 'ETHICS IN SOFTWARE'),
(22, NOW(), NOW(), 0, 'SOFT_ARCH', 'هندسة البرمجيات', 'SOFTWARE ARCHITECTURE'),
(23, NOW(), NOW(), 0, 'PROJ_MGMT', 'إدارة المشاريع', 'PROJECT MANAGEMENT'),
(24, NOW(), NOW(), 0, 'IT_MGMT', 'إدارة تقنية المعلومات', 'IT MANAGEMENT'),
(25, NOW(), NOW(), 0, 'COMP_THEORY', 'نظرية الحوسبة', 'COMPUTATIONAL THEORY'),
(26, NOW(), NOW(), 0, 'QUANT_COMPUT', 'الحوسبة الكمية', 'QUANTUM COMPUTING'),
(27, NOW(), NOW(), 0, 'DATA_ANALYTICS', 'تحليلات البيانات', 'DATA ANALYTICS'),
(28, NOW(), NOW(), 0, 'COMP_NETWORKS', 'شبكات الكمبيوتر', 'COMPUTER NETWORKS'),
(29, NOW(), NOW(), 0, 'INFO_SYS', 'نظم المعلومات', 'INFORMATION SYSTEMS'),
(30, NOW(), NOW(), 0, 'VIRT_REALITY', 'الواقع الافتراضي', 'VIRTUAL REALITY');
